const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

function formatUsd(cents) {
  const n = Math.round(Number(cents) || 0) / 100;
  return n.toLocaleString('en-US', { style: 'currency', currency: 'USD' });
}

/**
 * Writes a signed payslip PDF to disk. Content mirrors the digital attestation record.
 * @param {object} opts
 * @param {string} opts.outputPath absolute path to .pdf file
 * @param {{ fullName: string, employeeCode: string, jobTitleName?: string | null }} opts.employee
 * @param {{ year: number, month: number, label: string }} opts.period
 * @param {object} opts.breakdown result of computePayslip (gross, net, deductions, …)
 * @param {{ signatureText: string, signedAt: string, ipAddress: string | null }} opts.signature
 */
function writePayslipPdf(opts) {
  const { outputPath, employee, period, breakdown, signature } = opts;
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER', margin: 54 });
    const stream = fs.createWriteStream(outputPath);
    doc.pipe(stream);

    doc.fontSize(18).text('Payslip', { underline: false });
    doc.moveDown(0.25);
    doc.fontSize(11).fillColor('#333333');
    doc.text(`Pay period: ${period.label}`);
    doc.text(`Employee: ${employee.fullName} (${employee.employeeCode})`);
    if (employee.jobTitleName) {
      doc.text(`Job title: ${employee.jobTitleName}`);
    }
    doc.moveDown();

    doc.fontSize(12).fillColor('#000000').text('Earnings and deductions', { underline: true });
    doc.moveDown(0.35);
    doc.fontSize(10).fillColor('#222222');

    const rows = [
      ['Base salary (monthly)', formatUsd(breakdown.baseSalaryMonthlyCents)],
      ['Overtime pay', formatUsd(breakdown.overtimePayCents)],
      ['Bonus', formatUsd(breakdown.bonusCents)],
      ['Gross', formatUsd(breakdown.grossCents)],
      ['Income tax', `−${formatUsd(breakdown.deductions.incomeTaxCents)}`],
      ['Retirement', `−${formatUsd(breakdown.deductions.retirementCents)}`],
      ['Other deductions', `−${formatUsd(breakdown.deductions.otherCents)}`],
      ['Net pay', formatUsd(breakdown.netCents)],
    ];

    for (const [label, value] of rows) {
      doc.text(`${label}: ${value}`, { continued: false });
    }

    doc.moveDown(1.2);
    doc.fontSize(12).fillColor('#000000').text('Digital attestation', { underline: true });
    doc.moveDown(0.35);
    doc.fontSize(10).fillColor('#222222');
    const ipLine = signature.ipAddress ? `Signer IP: ${signature.ipAddress}` : 'Signer IP: (not recorded)';
    doc.text(
      `I, ${signature.signatureText}, attest that I have reviewed this payslip for ${period.label} ` +
        'and that the amounts shown reflect my understanding of this pay period.',
      { align: 'left' }
    );
    doc.moveDown(0.5);
    doc.text(`Signed at (UTC): ${signature.signedAt}`);
    doc.text(ipLine);
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#666666').text('This document was generated by the employer payslip system.', {
      align: 'left',
    });

    doc.end();
    stream.on('finish', () => resolve(undefined));
    stream.on('error', reject);
  });
}

module.exports = { writePayslipPdf, formatUsd };
